require('singhayu/telescope')
require('singhayu/lightline')
require('singhayu/gitsigns')
require('singhayu/lsp')
require('singhayu/treesitter')
require('singhayu/bufferline')
require('singhayu/nvimtree')
require('singhayu/nvimwebdevicons')
